apiVersion: v1
kind: Pod
metadata:
  name: portal-service-tank
  namespace: alexey-testload
spec:
  containers:
  - name: tank
    image: yandex/yandex-tank
    command: ["yandex-tank", "-c", "config/load.yaml"]
    volumeMounts:
    - name: config-volume
      mountPath: /var/loadtest/config
  volumes:
  - name: config-volume
    configMap:
      name: portal-service-ammo
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: cc-rb-02
