apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-service-ammo
  namespace: alexey-testload
data:
  ammo.txt: |
    empty_query	323000000
    empty_query	323500000
    empty_query	324000000
    empty_query	324500000
    empty_query	325000000
  load.yaml: |
    phantom:
      enabled: false
    bfg:
      enabled: true
      ammofile: config/ammo.txt
      gun_config:
        class_name: LoadTest
        module_path: ./test/
        module_name: test
      gun_type: ultimate
      instances: 10
      load_profile:
        load_type: instances
        schedule: const(10, 60s)
      loop: 2
    console:
      enabled: false
    telegraf:
      enabled: false
