apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-service-ammo
  namespace: alexey-testload
data:
  ammo.txt: |
    single_instruction	301267102
  load.yaml: |
    phantom:
      enabled: false
    bfg:
      enabled: true
      ammofile: config/ammo.txt
      gun_config:
        class_name: LoadTest
        module_path: ./test/
        module_name: test
      gun_type: ultimate
      instances: 1
      load_profile:
        load_type: instances
        schedule: const(1, 60s)
      loop: 1
    console:
      enabled: false
    telegraf:
      enabled: false
